# Generated by Django 3.0.4 on 2020-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='system', max_length=30, null=True)),
                ('change_time', models.DateTimeField(auto_now=True, null=True)),
                ('change_user', models.CharField(default='system', max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('positive', models.IntegerField(null=True)),
                ('positiveIncrease', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
    ]
