# Generated by Django 3.0.4 on 2020-03-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral', '0002_stats_totaltestresultsincrease'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='system', max_length=30, null=True)),
                ('change_time', models.DateTimeField(auto_now=True, null=True)),
                ('change_user', models.CharField(default='system', max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
